# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from smarp_msgs/recogObj.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class recogObj(genpy.Message):
  _md5sum = "4f3360b6f6ebe0d68e5b19307f35dc6c"
  _type = "smarp_msgs/recogObj"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool lines
bool light
bool stopline
bool object"""
  __slots__ = ['lines','light','stopline','object']
  _slot_types = ['bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       lines,light,stopline,object

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(recogObj, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.lines is None:
        self.lines = False
      if self.light is None:
        self.light = False
      if self.stopline is None:
        self.stopline = False
      if self.object is None:
        self.object = False
    else:
      self.lines = False
      self.light = False
      self.stopline = False
      self.object = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.lines, _x.light, _x.stopline, _x.object))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.lines, _x.light, _x.stopline, _x.object,) = _get_struct_4B().unpack(str[start:end])
      self.lines = bool(self.lines)
      self.light = bool(self.light)
      self.stopline = bool(self.stopline)
      self.object = bool(self.object)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.lines, _x.light, _x.stopline, _x.object))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.lines, _x.light, _x.stopline, _x.object,) = _get_struct_4B().unpack(str[start:end])
      self.lines = bool(self.lines)
      self.light = bool(self.light)
      self.stopline = bool(self.stopline)
      self.object = bool(self.object)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
